### ISSUE TITLE
是否考虑更换oauth授权服务

### ISSUE THREAD

**Issue by Hatsuhikari** [wuyouzhuguli/FEBS-Cloud#10]
[spring-security-oauth被废弃了，功能整合到spring-security5.2.x，不再支持Authorization Server](https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide) ，大佬是否考虑其它oauth授权，比如Keycloak？

**Comment by zonqiannet** [comment]
是否升级下教程 5.2.x？？
