### ISSUE TITLE
考不考虑使用spring-boot-starter方式封装

### ISSUE THREAD

**Issue by AmadeusSys** [wuyouzhuguli/FEBS-Cloud#14]
### 问题描述
就像spring-boot-starter-web之类的方式实现，配置一下马上使用

**Comment by wuyouzhuguli** [comment]
模块驱动也是通过一个注解就能开启某项功能，不过后续会有模块采用starter形式封装。

**Comment by AmadeusSys** [comment]
业务模块能和框架解耦就比较简洁，common模块可以发布到一个独立的制品厂库，cloud做成模块驱动一键启用，岂不是6的飞起。

**Comment by wuyouzhuguli** [comment]
嗯，近期会更新。

**Comment by wuyouzhuguli** [comment]
已经更新。
