### ISSUE TITLE
按照你所说，token不合法

### ISSUE THREAD

**Issue by Drallyzhu** [wuyouzhuguli/FEBS-Cloud#16]
![image](https://user-images.githubusercontent.com/32667672/79180196-e0ecb180-7e3b-11ea-85b5-52688979aefe.png)

找代码也没找到哪里校验这个，根据你所说，Authorization  是admin:123456 加密，因为数据库就是这个账户

**Comment by wuyouzhuguli** [comment]
Authorization 用的是febs:123456 base64加密值。
