### ISSUE TITLE
弱弱的问一句接入skywalking么

### ISSUE THREAD

**Issue by dlhf** [wuyouzhuguli/FEBS-Cloud#2]
弱弱的问一句接入skywalking么

**Comment by wuyouzhuguli** [comment]
TODO

**Comment by wuyouzhuguli** [comment]
已整合：[http://123.206.206.203:8080/](http://123.206.206.203:8080/)

**Comment by yuuki80code** [comment]
> 已整合：http://123.206.206.203:8080/

你咋这么神速？学习能力无敌啊

**Comment by wuyouzhuguli** [comment]
@yuuki80code CTO第一时间赶过来嘲笑😕

**Comment by sonake** [comment]
太牛批了，分我点功力，鸟哥太强了！cto也很强

**Comment by wuyouzhuguli** [comment]
@sonake 云大佬第二时间赶过来嘲笑😕
