### ISSUE TITLE
建议权限功能细化，区分菜单权限和接口权限

### ISSUE THREAD

**Issue by aprilfish** [wuyouzhuguli/FEBS-Cloud#5]
RT
实践中发现标准的RBAC模型并不完全适合前后端分离的场景，一个页面上可能会有多个接口调用，同一个接口也可能会在多个页面被调用，所以我觉得需要将两者分开，区分菜单权限和接口权限，由开发人员维护菜单（页面）和接口的关系，网关层只需要对接口权限进行检查，系统使用者通过设置菜单权限间接的管理接口权限，接口权限对用户透明，这样逻辑更清晰。看到一个项目SpringBlade似乎也是这种思路。

**Comment by wuyouzhuguli** [comment]
这样划分意义不大吧，简单问题复杂化。
