### ISSUE TITLE
关于登陆帐号密码明码的问题

### ISSUE THREAD

**Issue by q1anyi** [wuyouzhuguli/FEBS-Cloud#6]
### 问题描述
看过作者的源码，貌似帐号和密码在登陆的时候前后端传参的时候没有经过加密，后段采用的是Spring security的passwordEncoder.encode的方法去生成用户密码，如果用这种方式的话前端用什么方法去加密传参呢，貌似passwordEncoder.encode方法对相同密码每次生成的密码都不一样，或者考虑使用md5+salt加密传参？

**Comment by wuyouzhuguli** [comment]
参数要加密的化推荐非对称加密，其实https是最简单也是最好的选择。
