### ISSUE TITLE
是否考虑升级springcloud Alibaba到毕业版本2.1.1及引入Dubbo吗？

### ISSUE THREAD

**Issue by heishuang** [wuyouzhuguli/FEBS-Cloud#7]
Hi,大佬，你好：我看现在工程中的springcloud Alibaba是孵化器版本0.9.0，会考虑升级springcloud Alibaba到毕业版本2.1.1及引入Dubbo吗？

**Comment by wuyouzhuguli** [comment]
GroupId 为org.springframework.cloud的才是Spring Cloud分支；引入dubbo的目的是？

**Comment by heishuang** [comment]
我看版本说明中新版本GroupId改为com.alibaba.cloud，不知道GroupId 为org.springframework.cloud的是否还会继续更新
https://github.com/alibaba/spring-cloud-alibaba/wiki/版本说明
dubbo在内部传输上性能应该更好些，而且现在可以和其他组件兼容到一起，后续dubbo是不是也会发展的更好些

**Comment by wuyouzhuguli** [comment]
随着版本的推进，再考虑是否更换吧，现在先维持现状了。dubbo的功能spring cloud都有响应的组件实现，所以习惯spring cloud一把梭了，暂不考虑加入dubbo。

**Comment by heishuang** [comment]
ok，我个人比较喜欢搞阿里全家桶，^_^

**Comment by wuyouzhuguli** [comment]
话说回来，阿里搞两个groupId着实有点迷= =

**Comment by heishuang** [comment]
GroupId 为org.springframework.cloud的应该是不用了，毕业版本时阿里和apache进行了沟通，最后阿里说服apache使用其自己的GroupId   com.alibaba.cloud了，后续版本应该都是这个了

**Comment by wuyouzhuguli** [comment]
既然取名spring cloud alibaba，感觉还是用org.springframework.cloud作为groupId更为贴切。总之等Spring Cloud H版本GA后，还没更新的话，就得考虑更换了。

**Comment by heishuang** [comment]
是apache自己的决定
其实这主要是由于Spring Cloud考虑简化自己的Release Train（即：Spring Cloud自身的版本管理），于是修改了发布政策：非Spring Cloud团队维护的Spring Cloud的子项目，一律使用自己的GroupId即可，不再强制使用 org.springframework.cloud 。
http://www.imooc.com/article/295059

**Comment by wuyouzhuguli** [comment]
感谢大佬科普👍

**Comment by heishuang** [comment]
我也是前两天项目刚升的级 哈哈

**Comment by sonake** [comment]
鸟哥牛皮！

**Comment by wuyouzhuguli** [comment]
已升级已替换，请知悉。
